### ISSUE TITLE
Topic Structure Refactor

### ISSUE THREAD

**Issue by nampereira** [arenaxr/arena-persist#8]
1. New scene subtopics that users subscribe/publish to:
```
   <realm>/s/<namespace>/<scenename>/u/
   <realm>/s/<namespace>/<scenename>/g/
   <realm>/s/<namespace>/<scenename>/p/
```
2. Shorter proc: `<realm>/proc -> <realm>/p`
3. Marker detections go to: `<realm>/d/public/m `(replace `<realm>/g/a`)
4. Add userid to network latency topic 
5. Event and camera messages refactor 
6. Change ‘apriltag’ detection message type to ‘marker’ 
7. New ‘device_data’ type for device data
8. Change chat topics o=pub; p=priv

Details:
https://docs.google.com/presentation/d/1MRfo1IiIOiseMZ9BSAp-ksWmTouq9SW8RDAf8GKfnag/edit?usp=sharing

**Comment by mwfarb** [comment]
Closed in #26
